config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  
  resources :artists do
    resources :albums do 
      resources :songs
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many   :songs
  belongs_to :artist

  validates :title, presence: true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums
  has_many :songs

  validates :name, presence: true
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :songs

  validates :name, presence: true
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  validates :name, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album
  belongs_to :artist
  belongs_to :genre

  validates :title, presence: true
end

app/models/song_playlist.rb
class SongPlaylist < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
end

app/controllers/albums_controller.rb
class AlbumsController < ArtistsController

  def new 
    @artist = get_artist
    @album = @artist.albums.new 
  end

  def create 
    @artist = get_artist
    @album = @artist.albums.new(album_params)
    if @album.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
    @artist = get_artist
    @album = get_album(@artist)
  end

  def update
    @artist = get_artist
    @album = get_album(@artist)
    if @album.update_attributes(album_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist = get_artist
    @album = get_album(@artist)
    @album.destroy
    redirect_to artist_path(@artist)
  end


  private

  def get_artist
    Artist.find(params[:artist_id])
  end 

  def get_album
    Artist.album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end

  def show
    @artist = get_artist
  end

  def edit
    @artist = get_artist
  end

  def update
    @artist = get_artist
    if @artist.update_attributes(artist_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist = get_artist
    @artist.destroy
    redirect_to artists_path
  end

  private

  def get_artist
    Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :bio)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
def new
    @artist = get_artist
    @album = get_album(@artist)
    @song = @album.songs.new
  end

  def create
    @artist = get_artist
    @album = get_album(@artist)
    @song = @album.songs.new(song_params)
    @song.artist = @artist
    if @song.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def edit
    @artist = get_artist
    @album = get_album(@artist)
    @song = @album.songs.find(params[:id])
  end

  def update
    @artist = get_artist
    @album = get_album(@artist)
    @song = @album.songs.find(params[:id])
    if @song.update_attributes(song_params)
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist = get_artist
    @album = get_album(@artist)
    @song = @album.songs.find(params[:id])
    @song.destroy
    redirect_to artist_path(@artist)
  end

  private

  def get_artist
    Artist.find(params[:artist_id])
  end

  def get_album(artist)
    artist.albums.find(params[:album_id])
  end

  def song_params
    params.require(:song).permit(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<div class="content__container">
  <%= link_to "Add Album", new_album_path%> - - <%= link_to "Back To Artists", artists_path%>
  
</div>

app/views/artists/index.html.erb
<div class="content__container">
  <%= link_to "Add Artist", new_artist_path%>
  <ul>
  <% @artists.each do |a| %>
    <li>
      <%= a.name %> - - <%= link_to "Remove Artist", artist_path(a), :method => :get %>
    </li>
  <% end %>
</ul>
</div>

app/views/artists/new.html.erb
<% @title = "Add An Artist" %>

<div class="content__container">
  <h1>Add A New Artist</h1>

  <%= form_for @artist do |a| %>
    <% if @artist.errors.full_messages.present? %>
      <ul>
        <% @artist.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div>
      <%= a.label :name %>
      <%= a.text_field :name %>
    </div>
    <div>
      <%= a.submit "Add artist" %>
      <%= link_to "Back To Artists", artists_path%>
    </div>
  <% end %>
</div>

app/views/artists/show.html.erb
<div class="content__container">
  <%= link_to "Add Album", new_album_path :method => :get %> - - <%= link_to "Back To Artists", artists_path%>
  
</div>

app/views/home/index.html.erb
<div class="content__container">
  <p>You can use this app to manage your personal collection of artists and their albums.  Feel free to create, edit and delete to you heart's content.  Click the link below to get started!</p>

  <%= link_to "View Artists", artists_path, class: "link__styles"%>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedResources52</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="home__container">
    <h1>Manage Artists</h1>
    <%= yield %>
  </div>
</body>
</html>